# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('age', models.EmailField(blank=True, max_length=70)),
                ('group', models.CharField(choices=[('A', 'Age < 12'), ('B', '13 > Age > 22'), ('C', '23 > Age > 35'), ('D', 'Age > 36')], default='A', max_length=1)),
                ('language', models.CharField(choices=[('EN', 'English'), ('TN', 'Tamil'), ('KA', 'Kannada'), ('TE', 'Telegu'), ('MA', 'Malayalam'), ('HI', 'Hindi')], default='EN', max_length=2)),
                ('mobile_number', models.CharField(max_length=12)),
                ('email_id', models.EmailField(blank=True, max_length=70)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
