# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
